name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-2025
    timeout-minutes: 1
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=10TgpxMhm4RWpb4u2PmAMRbueuO-DbP9n&export=download&authuser=0&confirm=t&uuid=5c89a59b-041d-4050-8da7-7102b0ceb2c7" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat

   
