name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-2025
    timeout-minutes: 120

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1CElGc_j0h1f8b5iS6rAehPg8Ax_b97XH&export=download&confirm=t&uuid=3da302dd-20bc-4a74-9aec-c47a1ff7e277" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
